Args = -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -H:IncludeResources=application.*\\.properties \
       --initialize-at-run-time=io.lettuce.core \
       --initialize-at-run-time=org.springframework.data.redis

